### ISSUE TITLE
Creating a Super User for Django Backend

### ISSUE THREAD

**Issue by foopis23** [ThallesP/glitchtip-railway#1]
I can't figure out how to create a super user so that I can manage users in the admin portal. I know you are suppose to use manage.py, but not sure how to do that when its in railway. Can you help?

**Comment by ThallesP** [comment]
> I can't figure out how to create a super user so that I can manage users in the admin portal. I know you are suppose to use manage.py, but not sure how to do that when its in railway. Can you help?

Hi @foopis23, I'm afraid you can't create additional superusers, only the one that comes by default.

**Comment by foopis23** [comment]
Oh, there is a default one? I can't find the documentation for that in django or glitchtip. What is the default one? Maybe we could add to the readme or the railway template content documenting the default credentials?

**Comment by ThallesP** [comment]
> Oh, there is a default one? I can't find the documentation for that in django or glitchtip. What is the default one? Maybe we could add to the readme or the railway template content documenting the default credentials?

Ohh I think I'm the wrong here, by superuser I mean the user that comes by default when creating the first user in open registration.

**Comment by foopis23** [comment]
> > Oh, there is a default one? I can't find the documentation for that in django or glitchtip. What is the default one? Maybe we could add to the readme or the railway template content documenting the default credentials?
> 
> Ohh I think I'm the wrong here, by superuser I mean the user that comes by default when creating the first user in open registration.

Ohhh, I see. Man it would be so nice if railway had a thing similar to docker exec 😢 

I'm working right now to see if I can't create a superuser by spinning up the containers locally and using the railway cli to call manage.py. I'll post the results here once I can test it and then close the issue. I appreciate your time.

**Comment by foopis23** [comment]
I got side tracked, but I did get this working today. Here is how I did it.

1. Save this docker compose file somewhere on your machine
	```
	version: "3.8"
	x-environment:
	&default-environment
	DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
	SECRET_KEY: 96ad3484ad2f08b1ea8d3520d33e059a9e83fba53dd457ce60b8305009017874 # best to run openssl rand -hex 32
	PORT: 8000
	EMAIL_URL: consolemail:// # Example smtp://email:password@smtp_url:port https://glitchtip.com/documentation/install#configuration
	GLITCHTIP_DOMAIN: https://app.glitchtip.com # Change this to your domain
	DEFAULT_FROM_EMAIL: email@glitchtip.com # Change this to your email
	CELERY_WORKER_AUTOSCALE: "1,3"  # Scale between 1 and 3 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.
	CELERY_WORKER_MAX_TASKS_PER_CHILD: "10000"

	x-depends_on:
	&default-depends_on
	- postgres
	- redis

	services:
	postgres:
		image: postgres:15
		environment:
		POSTGRES_HOST_AUTH_METHOD: "trust"  # Consider removing this and setting a password
		restart: unless-stopped
		volumes:
		- pg-data:/var/lib/postgresql/data
	redis:
		image: redis
		restart: unless-stopped
	web:
		image: glitchtip/glitchtip
		depends_on: *default-depends_on
		ports:
		- "8000:8000"
		environment: *default-environment
		restart: unless-stopped
		volumes: 
		- uploads:/code/uploads
	worker:
		image: glitchtip/glitchtip
		command: ./bin/run-celery-with-beat.sh
		depends_on: *default-depends_on
		environment: *default-environment
		restart: unless-stopped
		volumes: 
		- uploads:/code/uploads
	migrate:
		image: glitchtip/glitchtip
		depends_on: *default-depends_on
		command: "./manage.py migrate"
		environment: *default-environment

	volumes:
	pg-data:
	uploads:
	```

2. In the same directory as the docker compose file run `docker-compose up -d`

3. Run `docker ps` to get the container id of the web container
4. Run `docker exec -u root -it <container id> bash` to get a bash shell in the container as root user
5. Run `bash <(curl -fsSL cli.new)` to install the railway cli
6. Do a browserless login with `railway login --browserless`
7. Run `railway link` and select the environment you want to link to
8. Run `railway run python manage.py createsuperuser` and follow the prompts
9. Run `exit` to exit the container
10. Run `docker-compose down` to stop the containers
